name: Policy Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@4ff59b6c35a46a87af3c3e641975743ee8fa0858
    with:
      policy_profile: flat
      policy_version: "1.0.1"
      policy_engine_ref: 4ff59b6c35a46a87af3c3e641975743ee8fa0858
