name: Policy Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@98487868a098e22647074c677a58633ce4fa19be
    with:
      policy_profile: flat
      policy_version: "1.0.2"
      policy_engine_ref: 98487868a098e22647074c677a58633ce4fa19be
