name: Policy Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@261f3f64bfe33a9762355c65cdc702b00110fea3  # v1.0.6
    with:
      policy_profile: flat
      policy_version: "1.0.6"
      policy_engine_ref: 261f3f64bfe33a9762355c65cdc702b00110fea3
